{
  "openapi": "3.0.0",
  "info": {
    "title": "Totalcheq Admin API",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://admin.totalcheq.com/api/v1",
      "variables": {}
    }
  ],
  "paths": {
    "/CreateTransactions": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Add transactions",
        "operationId": "Addtransactions",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/AddtransactionsRequest"
                },
                "description": "",
                "example": [
                  {
                    "api_key": "API Key",
                    "operation_id": "operation_id",
                    "log_id": "log id from external system",
                    "expense_code": "Kod rozhodu",
                    "pallet": "Kod rozhodnoi partii",
                    "date_of_expense": "Data rozhodu",
                    "timestamp": "2021-08-25 15:28:25.730",
                    "ext_sys_guid": "Product code in the external system",
                    "goods_sku": "Article",
                    "goods_name": "Goods name",
                    "wh_ext_sys_name": "The name of the warehouse, like - Sklad 3D",
                    "recipient_ext_sys_guid": "Code of the contractor-recipient of the order in the external system",
                    "recipient_name": "Name of the contractor-recipient",
                    "employee_ib": "Employee id",
                    "employee_pib": "Employee name",
                    "wh_area_name": "Warehouse area name",
                    "selection_cell": "Selection cell name",
                    "wh_area_id": "Warehouse area id",
                    "qty": "Quantity of goods"
                  },
                  {
                    "api_key": "API Key",
                    "operation_id": "operation_id",
                    "log_id": "log id from external system",
                    "expense_code": "Kod rozhodu",
                    "pallet": "Kod rozhodnoi partii",
                    "date_of_expense": "Data rozhodu",
                    "timestamp": "2021-08-25 15:28:25.730",
                    "ext_sys_guid": "Product code in the external system",
                    "goods_sku": "Article",
                    "goods_name": "Goods name",
                    "wh_ext_sys_name": "The name of the warehouse, like - Sklad 3D",
                    "recipient_ext_sys_guid": "Code of the contractor-recipient of the order in the external system",
                    "recipient_name": "Name of the contractor-recipient",
                    "employee_ib": "Employee id",
                    "employee_pib": "Employee name",
                    "wh_area_name": "Warehouse area name",
                    "selection_cell": "Selection cell name",
                    "wh_area_id": "Warehouse area id",
                    "qty": "Quantity of goods"
                  }
                ]
              },
              "example": [
                {
                  "api_key": "API Key",
                  "operation_id": "operation_id",
                  "log_id": "log id from external system",
                  "expense_code": "Kod rozhodu",
                  "pallet": "Kod rozhodnoi partii",
                  "date_of_expense": "Data rozhodu",
                  "timestamp": "2021-08-25 15:28:25.730",
                  "ext_sys_guid": "Product code in the external system",
                  "goods_sku": "Article",
                  "goods_name": "Goods name",
                  "wh_ext_sys_name": "The name of the warehouse, like - Sklad 3D",
                  "recipient_ext_sys_guid": "Code of the contractor-recipient of the order in the external system",
                  "recipient_name": "Name of the contractor-recipient",
                  "employee_ib": "Employee id",
                  "employee_pib": "Employee name",
                  "wh_area_name": "Warehouse area name",
                  "selection_cell": "Selection cell name",
                  "wh_area_id": "Warehouse area id",
                  "qty": "Quantity of goods"
                },
                {
                  "api_key": "API Key",
                  "operation_id": "operation_id",
                  "log_id": "log id from external system",
                  "expense_code": "Kod rozhodu",
                  "pallet": "Kod rozhodnoi partii",
                  "date_of_expense": "Data rozhodu",
                  "timestamp": "2021-08-25 15:28:25.730",
                  "ext_sys_guid": "Product code in the external system",
                  "goods_sku": "Article",
                  "goods_name": "Goods name",
                  "wh_ext_sys_name": "The name of the warehouse, like - Sklad 3D",
                  "recipient_ext_sys_guid": "Code of the contractor-recipient of the order in the external system",
                  "recipient_name": "Name of the contractor-recipient",
                  "employee_ib": "Employee id",
                  "employee_pib": "Employee name",
                  "wh_area_name": "Warehouse area name",
                  "selection_cell": "Selection cell name",
                  "wh_area_id": "Warehouse area id",
                  "qty": "Quantity of goods"
                }
              ]
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/addGoodsLoading": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Add goods loading",
        "operationId": "Addgoodsloading",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddgoodsloadingRequest"
              },
              "example": {
                "api_key": "API Key",
                "operation_id": "operation_id",
                "log_id": "log id from external system",
                "pallet": "Kod rozhodnoi partii",
                "timestamp_start": "2021-08-25 15:28:25.730",
                "timestamp_end": "2021-08-25 15:31:40.530"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/addPalletPacking": {
      "post": {
        "tags": [
          "Misc"
        ],
        "summary": "Add pallet packing",
        "operationId": "Addpalletpacking",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AddpalletpackingRequest"
              },
              "example": {
                "api_key": "API Key",
                "operation_id": "operation_id",
                "log_id": "log id from external system",
                "pallet": "Kod rozhodnoi partii",
                "timestamp_start": "2021-08-25 15:28:25.730",
                "timestamp_end": "2021-08-25 15:31:40.530"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "AddtransactionsRequest": {
        "title": "AddtransactionsRequest",
        "required": [
          "api_key",
          "operation_id",
          "log_id",
          "expense_code",
          "pallet",
          "date_of_expense",
          "timestamp",
          "ext_sys_guid",
          "goods_sku",
          "goods_name",
          "wh_ext_sys_name",
          "recipient_ext_sys_guid",
          "recipient_name",
          "employee_ib",
          "employee_pib",
          "wh_area_name",
          "selection_cell",
          "wh_area_id",
          "qty"
        ],
        "type": "object",
        "properties": {
          "api_key": {
            "type": "string"
          },
          "operation_id": {
            "type": "string"
          },
          "log_id": {
            "type": "string"
          },
          "expense_code": {
            "type": "string"
          },
          "pallet": {
            "type": "string"
          },
          "date_of_expense": {
            "type": "string"
          },
          "timestamp": {
            "type": "string"
          },
          "ext_sys_guid": {
            "type": "string"
          },
          "goods_sku": {
            "type": "string"
          },
          "goods_name": {
            "type": "string"
          },
          "wh_ext_sys_name": {
            "type": "string"
          },
          "recipient_ext_sys_guid": {
            "type": "string"
          },
          "recipient_name": {
            "type": "string"
          },
          "employee_ib": {
            "type": "string"
          },
          "employee_pib": {
            "type": "string"
          },
          "wh_area_name": {
            "type": "string"
          },
          "selection_cell": {
            "type": "string"
          },
          "wh_area_id": {
            "type": "string"
          },
          "qty": {
            "type": "string"
          }
        },
        "example": {
          "api_key": "API Key",
          "operation_id": "operation_id",
          "log_id": "log id from external system",
          "expense_code": "Kod rozhodu",
          "pallet": "Kod rozhodnoi partii",
          "date_of_expense": "Data rozhodu",
          "timestamp": "2021-08-25 15:28:25.730",
          "ext_sys_guid": "Product code in the external system",
          "goods_sku": "Article",
          "goods_name": "Goods name",
          "wh_ext_sys_name": "The name of the warehouse, like - Sklad 3D",
          "recipient_ext_sys_guid": "Code of the contractor-recipient of the order in the external system",
          "recipient_name": "Name of the contractor-recipient",
          "employee_ib": "Employee id",
          "employee_pib": "Employee name",
          "wh_area_name": "Warehouse area name",
          "selection_cell": "Selection cell name",
          "wh_area_id": "Warehouse area id",
          "qty": "Quantity of goods"
        }
      },
      "AddgoodsloadingRequest": {
        "title": "AddgoodsloadingRequest",
        "required": [
          "api_key",
          "operation_id",
          "log_id",
          "pallet",
          "timestamp_start",
          "timestamp_end"
        ],
        "type": "object",
        "properties": {
          "api_key": {
            "type": "string"
          },
          "operation_id": {
            "type": "string"
          },
          "log_id": {
            "type": "string"
          },
          "pallet": {
            "type": "string"
          },
          "timestamp_start": {
            "type": "string"
          },
          "timestamp_end": {
            "type": "string"
          }
        },
        "example": {
          "api_key": "API Key",
          "operation_id": "operation_id",
          "log_id": "log id from external system",
          "pallet": "Kod rozhodnoi partii",
          "timestamp_start": "2021-08-25 15:28:25.730",
          "timestamp_end": "2021-08-25 15:31:40.530"
        }
      },
      "AddpalletpackingRequest": {
        "title": "AddpalletpackingRequest",
        "required": [
          "api_key",
          "operation_id",
          "log_id",
          "pallet",
          "timestamp_start",
          "timestamp_end"
        ],
        "type": "object",
        "properties": {
          "api_key": {
            "type": "string"
          },
          "operation_id": {
            "type": "string"
          },
          "log_id": {
            "type": "string"
          },
          "pallet": {
            "type": "string"
          },
          "timestamp_start": {
            "type": "string"
          },
          "timestamp_end": {
            "type": "string"
          }
        },
        "example": {
          "api_key": "API Key",
          "operation_id": "operation_id",
          "log_id": "log id from external system",
          "pallet": "Kod rozhodnoi partii",
          "timestamp_start": "2021-08-25 15:28:25.730",
          "timestamp_end": "2021-08-25 15:31:40.530"
        }
      }
    },
    "securitySchemes": {
      "API-Key": {
        "type": "apiKey",
        "description": "",
        "name": "X-API-Key",
        "in": "header"
      }
    }
  },
  "security": [
    {
      "API-Key": []
    }
  ],
  "tags": [
    {
      "name": "Misc",
      "description": ""
    }
  ]
}
